// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irnkilorodqvhizmujtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlybmtpbG9yb2Rxdmhpem11anRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMjM2OTUsImV4cCI6MjA2NDU5OTY5NX0.9wRY7Qj1NTEWukOF902PhpPoR_iASywfAqkTQP6ySOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);